/// \file GameDefines.h
/// \brief Game specific defines.

#pragma once

#include "Defines.h"

/// \brief Sprite type.
///
/// Note: NUM_SPRITES must be last.

enum eSpriteType{
  // text
  STARTTEXT_SPRITE, CREDITSTEXT_SPRITE, TUTORIAL_1_SPRITE, TUTORIAL_2_SPRITE, TUTORIAL_3_SPRITE, TUTORIAL_4_SPRITE, TUTORIAL_5_SPRITE,
  //from blank game
  TEXTWHEEL_SPRITE, LOADGAME_SPRITE, DEATHSCREEN_SPRITE,
  //background
  BACKGROUND_SPRITE, WINSCREEN_SPRITE, 
  //world objects
  TILE_SPRITE, CHEST_SPRITE, STAIR_SPRITE, HEALTHOUTLINE_SPRITE, HEALTHBAR_SPRITE, BOSSHEALTH_SPRITE,
  //entities
  PLAYER_SPRITE, TURRET_SPRITE, GOBLIN_SPRITE, SKELETON_SPRITE, DEMON_SPRITE, BOSS_SPRITE,
  //Weapons
  SWORD_SPRITE, CROSS_SPRITE,
  //projectiles
  BULLET2_SPRITE, PUNCH_SPRITE, ARROW_SPRITE, LARGEFIREBALL_SPRITE, DEMONFIREBALL_SPRITE,
  //items
  HEALTH_POTION_GROUND_SPRITE, SPEED_POTION_GROUND_SPRITE, HEALTH_POTION_INVENTORY_SPRITE, SPEED_POTION_INVENTORY_SPRITE, SWORDGROUND_SPRITE, CROSSGROUND_SPRITE,
  LAMP_SPRITE,
  //particles
  SMOKE_SPRITE, SPARK_SPRITE,
  //debug and inventory
  GREENLINE_SPRITE, WHITELINE_SPRITE, REDLINE_SPRITE, CROSSINVENTORY_SPRITE, SWORDINVENTORY_SPRITE,
  NUM_SPRITES //MUST BE LAST

}; //eSpriteType
